In [1]:
from gerrychain import Graph
from merges import *

## Load in the graphs

In [2]:
for i in range(100000, 1100000, 100000):
    old_graph = Graph.from_json(f'AlternativePlans/graph_recom_{i}.json')

In [3]:
new_graph = Graph.from_json('ChainUtilityData/2018_all_votes_current_no_nan.json')

## Find mismatches

In [4]:
vista_ids_old = [old_graph.nodes[n]['VistaID'] for n in old_graph.nodes]
vista_ids_new = [new_graph.nodes[n]['VistaID'] for n in new_graph.nodes]

for j, vista_id in enumerate(vista_ids_old):
    if vista_id not in vista_ids_new:
        print(j, vista_id, end='\n')
print('-')
for i, vista_id in enumerate(vista_ids_new):
    if vista_id not in vista_ids_old:
        print(i, vista_id, end='\n')

230 MIDV:2ENO 4:1CC 25:2ENO 4:2CC 25:1CC 16:1CC 16:2
-
230 MIDV:2
259 ENO 4:1ENO 4:2
265 CC 25:2CC 25:1
267 CC 16:1CC 16:2


It looks like new precincts 230, 259, 265, 267 all refer to the old precinct 230.

In [5]:
# Create a merge object to create a mapping
m = Merge(n=2643)
m.add(set([230, 259, 265, 267]))

## Map the 10 recom assignments to the new precincts and save

In [6]:
for i in range(100000, 1100000, 100000):
    old_graph = Graph.from_json(f'AlternativePlans/graph_recom_{i}.json')
    new_graph = Graph.from_json('ChainUtilityData/2018_all_votes_current_no_nan.json')
    
    # Use the new graph structure but update the assignments to the old ones
    for new, old in enumerate(m.get_dissolve()):
        new_graph.nodes[new]['US_Distric'] = old_graph.nodes[old]['US_Distric']
    
    new_graph.to_json(f'AlternativePlans/graph_recom_{i}_new.json')

In [7]:
# Check
for i in range(100000, 1100000, 100000):
    new_graph = Graph.from_json(f'AlternativePlans/graph_recom_{i}_new.json')